version: '3'

services:

  db:
    image: mysql:5.7.21
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: docker
       MYSQL_DATABASE: docker
    ports:
      - '3306:3308'

  web:
    build:
       context: .
       dockerfile: Dockerfile
    command: |
      sh -c 'python manage.py makemigrations && \
                     python manage.py migrate && \
                     python manage.py runserver 0.0.0.0:8000'
    restart: always
    environment:
       MYSQL_DATABASE: docker
       MYSQL_USER: root
       MYSQL_PASSWORD: docker
       MYSQL_HOST: localhost
       MYSQL_PORT: 3306
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - ".:/app:rw"
      - "./data:/data:rw"
    depends_on:
      - db
      - web

