version: '3'

services:

  db:
    image: mysql:5.7.21
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: docker
       MYSQL_DATABASE: docker
    ports:
      - '3306:3306'
    expose:
      - "3306"

  web:
    build:
       context: .
       dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    environment:
       MYSQL_DATABASE: docker
       MYSQL_USER: root
       MYSQL_PASSWORD: docker
       MYSQL_HOST: docker
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
