version: '3'

services:
  db:
    image: mysql:5.7.21
    command: --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_ROOT_PASSWORD: docker
       MYSQL_DATABASE: docker
       MYSQL_USER: docker
       MYSQL_PASSWORD: docker
    ports:
      - '3306:3306'

  web:
    build: 
       context: .
       dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
       MYSQL_DATABASE: docker
       MYSQL_USER: docker
       MYSQL_PASSWORD: docker
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db