version: '3'

services:

  db:
    image: mysql:5.7.21
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: docker
       MYSQL_DATABASE: db
    ports:
      - '3306:3306'
    expose:
      - "3306"


  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

  web:
    build:
       context: .
       dockerfile: Dockerfile
#    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    command: |
      sh -c 'python manage.py makemigrations && \
                     python manage.py migrate && \
                     python manage.py runserver 0.0.0.0:8000'
    restart: always
    environment:
       MYSQL_DATABASE: db
       MYSQL_USER: root
       MYSQL_PASSWORD: docker
       MYSQL_HOST: localhost
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
