# Generated by Django 3.0.7 on 2020-06-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhours',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
