# Generated by Django 3.0.7 on 2020-06-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0003_auto_20200629_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workhours',
            old_name='hours',
            new_name='duration',
        ),
    ]
