# Generated by Django 3.0.7 on 2020-06-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0004_auto_20200629_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='duration',
            field=models.DateTimeField(null=True),
        ),
    ]
