# Generated by Django 3.0.7 on 2020-06-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_app', '0005_auto_20200630_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
